### PR TITLE
South-eastern-countries

### LINKED ISSUE #22: Add South-eastern asia countries
If you're working on this ticket leave a comment, so no two people do the same work. After 2h of the comment, I'll start accepting other volunteers.

The PR to fix this issue should include all the countries with all the data.

# List of countries
Brunei Darussalam
Cambodia
Indonesia
Laos
Malaysia
Myanmar
Philippines
Singapore
Thailand
Timor-Leste
Vietnam

### PR DESCRIPTION
**Pull request by vickywane**
## Overview
This PR adds data for south-eastern countries to the repository.

## Changes
- Added country data for 12 south-eastern countries/regions
- 67 lines of additions across 12 files
- 15 commits with incremental improvements

## Related Issue
Closes #22

## Type of Change
- [x] Data addition
- [ ] Bug fix
- [ ] Documentation update

### CODE REVIEW

**Review by lsmoura — CHANGES_REQUESTED** [review]
A few issues here:
* The flag field is not in unicode format. Look here: https://emojipedia.org/flags/
* The "alpha2" and "alpha3" field values should all be lowercase
* Let's not remove `con.yaml`

**Comment by vickywane** [comment]
Hi , i've made needed changes .

**Comment by sergioaboard** [comment]
Hi!

The flags are not there. For example, this is the flag for Indonesia: 🇮🇩

You need to revert `con.yaml`. You can use this to get it back:

`git checkout origin/master data/con.yaml`

And commit the results.

**Comment by vickywane** [comment]
@sergioaboard i ran a look up on con.yaml and pasted the content from my local git history

**Comment by vickywane** [comment]
I've seen some errors . I would fix it in some minutes

**Comment by vickywane** [comment]
Thanks for the fix . I've been moving since my last comment. I was hoping to work on it soon

**Pull request merged**
